version: 2

models:
  - name: hub_user
    description: "Hub table for unique business keys from stg_users"
    columns:
      - name: user_hk
        description: "Surrogate key for user_id"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Business key"
        tests:
          - not_null
      - name: load_date
        description: "Timestamp when the record was loaded"
      - name: dbt_batch_id
        description: "DBT invocation ID to track batch loads"

  - name: sat_user
    description: "Satellite table capturing user descriptive attributes"
    columns:
      - name: user_hk
        description: "Foreign key to hub_user"
        tests:
          - not_null
      - name: hashdiff
        description: "Hash of all descriptive attributes for change detection"
        tests:
          - not_null
      - name: birth_year
        description: "User's year of birth"
      - name: country
        description: "Country of the user"
      - name: plan
        description: "User subscription plan"
      - name: user_settings_crypto_unlocked
        description: "Whether crypto settings are enabled"
      - name: marketing_push
        description: "Push marketing setting"
      - name: marketing_email
        description: "Email marketing setting"
      - name: num_contacts
        description: "Number of contacts"
      - name: load_date
        description: "Timestamp when the record was loaded"
      - name: dbt_batch_id
        description: "DBT invocation ID to track batch loads"
