name: dbt CI
on:
  pull_request:
    branches: [ master, main ]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Second step: install python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

      - name: Install dbt
        run: pip install dbt-core dbt-postgres  # or your adapter

      - name: Run dbt checks
        run: |
          cd ./dbt/dbt_neobank
          dbt deps
          dbt build --select state:modified+ --fail-fast

      - name: Lint dbt models
        run: |
          sqlfluff lint
